Update build-sonarr.yml

diff --git a/.github/workflows/build-sonarr.yml b/.github/workflows/build-sonarr.yml
--- a/.github/workflows/build-sonarr.yml
+++ b/.github/workflows/build-sonarr.yml
@@ -4,6 +4,7 @@ permissions:
   issues: write  # Omogućava GitHub Actions-u upravljanje problemima
   discussions: write  # Omogućava GitHub Actions-u upravljanje diskusijama
 
+# Ostatak workflow-a
 name: Auto Build Sonarr
 
 on:
@@ -40,17 +41,23 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       # Dohvati najnoviju verziju Sonarr-a putem GitHub API-a
-      - name: Get latest Sonarr version
+      - name: Get latest Sonarr version from GitHub
         id: get_version
         run: |
-          VERSION=$(curl --silent "https://api.github.com/repos/Sonarr/Sonarr/releases/latest" | jq -r .tag_name)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          VERSION=$(curl -s https://api.github.com/repos/Sonarr/Sonarr/releases/latest | jq -r .tag_name)
+          if [ -z "$VERSION" ]; then
+            echo "Failed to fetch Sonarr version."
+            exit 1
+          fi
+          echo "Sonarr version fetched: $VERSION"
+          echo "SONARR_VERSION=$VERSION" >> $GITHUB_ENV
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
       # Provjera postoji li već image na Docker Hubu
       - name: Check if image already exists
         id: check_image
         run: |
-          image_tag="${{ env.IMAGE_NAME }}:${{ env.ARCH_TAG }}-${{ env.VERSION }}"
+          image_tag="${{ env.IMAGE_NAME }}:${{ env.ARCH_TAG }}-${{ github.sha }}"
           image_exists=$(docker manifest inspect $image_tag || echo "not found")
           if [[ $image_exists == *"not found"* ]]; then
             echo "Image not found. Proceeding with build."
@@ -71,19 +78,19 @@ jobs:
           platforms: ${{ env.PLATFORM }}
           build-args: |
             BUILD_DATE=${{ github.event.head_commit.timestamp }}
-            VERSION=${{ env.VERSION }}
+            VERSION=${{ github.sha }}
           tags: |
-            ${{ env.IMAGE_NAME }}:${{ env.ARCH_TAG }}-${{ env.VERSION }}
+            ${{ env.IMAGE_NAME }}:${{ env.ARCH_TAG }}-${{ github.sha }}
             ${{ env.IMAGE_NAME }}:${{ env.ARCH_TAG }}-latest
 
       # Obavijest o uspjehu putem Discorda
       - name: Send Discord notification on success
         if: env.image_exists == 'false'
         run: |
-          curl -X POST -H "Content-Type: application/json" -d '{"content": "New Sonarr image version '${{ env.VERSION }}' for ARM architecture has been built and pushed to Docker Hub."}' ${{ secrets.DISCORD_WEBHOOK }}
+          curl -X POST -H "Content-Type: application/json" -d '{"content": "New Sonarr image version has been built and pushed to Docker Hub."}' ${{ secrets.DISCORD_WEBHOOK }}
 
       # Obavijest o neuspjehu putem Discorda
       - name: Send Discord notification on failure
         if: failure()
         run: |
-          curl -X POST -H "Content-Type: application/json" -d '{"content": "Build failed for Sonarr image version '${{ env.VERSION }}' for ARM architecture. Please check the build logs."}' ${{ secrets.DISCORD_WEBHOOK }}
+          curl -X POST -H "Content-Type: application/json" -d '{"content": "Build failed for Sonarr image. Please check the build logs."}' ${{ secrets.DISCORD_WEBHOOK }}
